#!/bin/sh

# Set default environment variables
export AUTOHEAL_MODE=${AUTOHEAL_MODE:-"all"}
export AUTOHEAL_RESTART_EXITED=${AUTOHEAL_RESTART_EXITED:-"true"}
export AUTOHEAL_RESTART_UNHEALTHY=${AUTOHEAL_RESTART_UNHEALTHY:-"true"}
export AUTOHEAL_DEFAULT_POLICY=${AUTOHEAL_DEFAULT_POLICY:-"on-failure"}
export AUTOHEAL_MAX_ATTEMPTS=${AUTOHEAL_MAX_ATTEMPTS:-"5"}
export AUTOHEAL_CHECK_INTERVAL=${AUTOHEAL_CHECK_INTERVAL:-"5"}
export AUTOHEAL_DISCORD_WEBHOOK=${AUTOHEAL_DISCORD_WEBHOOK:-""}

# Start the autoheal process
exec python /app/autoheal.py
